### ISSUE TITLE
Incorrect filename

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/exercise-configure-dependabot#1]
This is probably expected behavior, but just wanted to confirm there's no better way to address this scenario. The scenario is: a user used the wrong filename. The behavior we see: incorrect filename but not from the established exercise feedback mechanisms. [Example](https://github.com/hectorsector/verbose-broccoli/runs/3745193440?check_suite_focus=true)

**Comment by mattdavis0351** [comment]
@hectorsector I'm getting a 404 when trying to view your example

**Comment by hectorsector** [comment]
🤦 sorry, made public now

**Comment by hectorsector** [comment]
The error message is descriptive enough, so I'm closing this out.
